defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=2"

pull_request_rules:
  - name: automerge to the base branch with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>=2"
      - base=main
      - label=A:automerge
      - check-success=test-11
      - check-success=test-12
      - check-success=test-21
      - check-success=test-22
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
           {{ title }} (#{{ number }})
           {{ body }}