# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Test 2

on:
  push:
    branches: [ main ]

jobs:
  test-21:
    runs-on: ubuntu-latest
    
    steps:
    - name: Info
      run: |
        echo "this is first test"

    - name: Random exit
      run: |
        res=$(($RANDOM%2))
        if [ $res != "0" ]; then
          echo "test passed!"
          exit 0
        else
          echo "test failed!"
          exit 1
        fi

  test-22:
    runs-on: ubuntu-latest
    
    steps:
    - name: Info
      run: |
        echo "this is second test"

    - name: Random exit
      run: |
        res=$(($RANDOM%2))
        if [ $res != "0" ]; then
          echo "test passed!"
          exit 0
        else
          echo "test failed!"
          exit 1
        fi